version: '3.7'

services:

  frontend:
    container_name: docker-container-template
    build: ./
    env_file: ./.env
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start